version: '2'
services:
  fogcontrolnode:
    build: target/docker/
    image: fogcontrolnode # to name the image
    ports:
      - "8080:8080"
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redisFCN
  redisFCN:
    image: redis
    ports:
      - "6380:6379"